-- local client = vim.lsp.start_client {
--   name = 'educationalsp',
--   cmd = { '/home/adibf/Documents/educationalsp/educationalsp' },
-- }
--
-- if not client then
--   vim.notify 'missing binary'
--   return
-- end
--
-- vim.api.nvim_create_autocmd('FileType', {
--   pattern = 'markdown',
--   callback = function()
--     vim.lsp.buf_attach_client(0, client)
--   end,
-- })
